name: neo4j_dart
description: >
  A Neo4j driver for Dart.
version: 0.2.0
author: Rasmus Eneman <rasmus@eneman.eu>
homepage: https://github.com/Pajn/Neo4jDart
dependencies:
  crypto: any
  http: ">=0.11.1+3 <0.12.0"
dev_dependencies:
  guinness: any
  unittest: <0.12.0
