name: neo4j_dart
description: >
  A Neo4j driver for Dart.
version: 0.3.0
author: Rasmus Eneman <rasmus@eneman.eu>
homepage: https://github.com/Pajn/Neo4jDart
dependencies:
  crypto: ">=0.9.0 <0.10.0"
  http: ">=0.11.1+3 <0.12.0"
  warehouse:
    git: https://github.com/Pajn/Warehouse.git
dev_dependencies:
  guinness: any
  unittest: ">= 0.11.0 <0.12.0"
