name: neo4j_dart
description: >
  A Neo4j driver for Dart.
version: 0.3.2
author: Rasmus Eneman <rasmus@eneman.eu>
homepage: https://github.com/Pajn/Neo4jDart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto:
  http:
  quiver:
