name: neo4j_dart
description: >
  A Neo4j driver for Dart.
version: 0.3.2
author: Rasmus Eneman <rasmus@eneman.eu>
homepage: https://github.com/Pajn/Neo4jDart

environment:
  sdk: '>=2.12.0'

dependencies:
  crypto:
  http:
  quiver:
  json_serializable:
  json_annotation: '>=4.5.0'
  dio:


dev_dependencies:
  build_runner:
  test:
