name: neo4j_dart
description: >
  A Neo4j driver for Dart.
version: 0.0.1
author: Rasmus Eneman <rasmus@eneman.eu>
homepage: https://github.com/Pajn/Neo4jDart
dependencies:
  http: any
dev_dependencies:
  guinness: any
  unittest: any
